# Structure de données avec Pandas

**Series** : tableau 1D indexé
- Une **Series** dans Pandas est un tableau 1D étiqueté
- C'est similaire à un tableau NumPy, mais avec des étiquettes d'index personnalisables
- Elle peut contenir n'importe quel type de données : nombres, chaînes, booléens, objets, etc.

**DataFrame** : tableau 2D indexé (lignes et colonnes), similaire à une feuille Excel ou une table SQL.

In [46]:
import pandas as pd

data = pd.Series([0.25, 0.5, 0.75, 1.0])

data.index    # IndexRange object ( une formule compressée ) : range(0, 4)
list(data.index)  # Tableau numpy des indices : array([0, 1, 2, 3])
data.values   # Tableau numpy des valeurs : array([0.25, 0.5, 0.75, 1.0])

array([0.25, 0.5 , 0.75, 1.  ])

## Index explicites (noms personnalisés)

Contrairement aux tableaux NumPy, il est possible de donner des noms personnalisés aux index :

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])

## DataFrame

Un **DataFrame** ressemble à un array 2D mais avec plus de flexibilité. On peut par exemple ajouter des noms aux colonnes. Un DataFrame est au minimum constitué de deux **Series** (deux colonnes).

- Chaque colonne est une **Series** avec un nom
- Chaque ligne est identifiée par un **index** (comme dans les Series)
- Il peut contenir plusieurs types de données (nombres, chaînes, booléens…)

| Propriété/Méthode | Description |
|---|---|
| `df.index` | Index des lignes (par défaut : 0, 1, 2…) |
| `df.columns` | Liste des noms de colonnes |
| `df.values` | Données sous forme de tableau NumPy |
| `df.dtypes` | Type de chaque colonne |
| `df.shape` | Dimensions du tableau (lignes, colonnes) |
| `df.mean(numeric_only=True)` | Moyenne par colonne |
| `df.sum(numeric_only=True)` | Somme par colonne |
| `df.sort_values("col")` | Trier par colonne |
| `df.groupby("col").mean()` | Grouper par colonne |
| `df.drop("col", axis=1)` | Supprimer une colonne |

In [ ]:
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Paris", "Lyon", "Marseille"]
}

df = pd.DataFrame(data)

In [ ]:
df["name"]           # Retourne une Series (une seule colonne)

df[["name", "age"]]  # Retourne un DataFrame (plusieurs colonnes)

df.loc['e']         # Par étiquette (index) → accès à la ligne 0 ( loc contrairement à iloc permet d'accéder à une ligne par son étiquette )

df.iloc[1]        # Par position → accès à la 2e ligne ( iloc permet d'accéder à une ligne par sa position )

df[df["age"] > 28]   # Sélectionne les personnes de plus de 28 ans

## Index

Un ou plusieurs groupes d'index permettent de localiser les données.

- Accéder à l'index : `df.index`
- Réinitialiser l'index : `df.reset_index(inplace=True)`
- Changer l'index : `df.set_index("name", inplace=True)`

## Créer un DataFrame

On peut créer un DataFrame à partir de plusieurs sources :

| Source | Syntaxe |
|---|---|
| D'une Series | `pd.DataFrame(population, columns=['population'])` |
| D'une liste de dictionnaires | `pd.DataFrame([{'a': i, 'b': 2 * i} for i in range(3)])` |
| D'un dictionnaire de Series | `pd.DataFrame({'population': population, 'area': area})` |
| D'un array NumPy 2D | `pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])` |
| Depuis un fichier CSV | `pd.read_csv(PATH)` |

## Accéder à un élément par son index

On peut accéder à une valeur comme dans un dictionnaire en passant l'étiquette de l'index.

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data['b']  # Résultat : 0.5

np.float64(0.5)

## Tester la présence d'un index

On peut vérifier si une clé est présente dans la Series.

In [11]:
'a' in data  # Résultat : True

'z' in data  # Résultat : False

False

## Obtenir les clés (index)

Équivalent de `.keys()` sur un dictionnaire.

In [ ]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

## Afficher tous les éléments

Chaque élément est retourné sous forme de tuple `(index, valeur)`.

In [ ]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

## Ajouter une nouvelle valeur

Si l'index n'existe pas, Pandas crée un nouvel élément.

In [4]:
data['e'] = 1.25

data

0    0.25
1    0.50
2    0.75
3    1.00
e    1.25
dtype: float64

## Slicing explicite (par label)

> Lorsque les étiquettes sont utilisées, la **borne supérieure est incluse**.

In [7]:
data[1:'e']

1    0.50
2    0.75
3    1.00
e    1.25
dtype: float64

## Slicing implicite (par position)

> Lorsque les entiers sont utilisés, la **borne supérieure est exclue**.

In [ ]:
data[0:2]

## Sélection avec un masque booléen

Un **masque booléen** est un tableau de booléens qui permet de filtrer les données selon une condition.

In [ ]:
data[(data > 0.3) & (data < 0.8)]
# Résultat : b    0.50
#            c    0.75

## Multi-indexation explicite

Permet de récupérer plusieurs éléments à la fois en passant une liste d'index.

In [ ]:
data[['a', 'e']]
# Résultat : a    0.25
#            e    1.25

## Indexation et sélection dans un DataFrame

In [17]:
data = pd.DataFrame(
{
    'age': [22, 35, 58, 44],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'score': [88.5, 92.3, 70.0, 85.2]
}, 
index=['a', 'b', 'c', 'd'])

data

   age     name  score
a   22    Alice   88.5
b   35      Bob   92.3
c   58  Charlie   70.0
d   44    David   85.2

### Accéder à une colonne

On récupère une colonne comme une **Series**.

In [18]:
data['name']
# Résultat : une Series contenant les prénoms

a      Alice
b        Bob
c    Charlie
d      David
Name: name, dtype: object

### Accéder à plusieurs colonnes

On passe une liste de noms de colonnes.

In [19]:
data[['name', 'score']]

      name  score
a    Alice   88.5
b      Bob   92.3
c  Charlie   70.0
d    David   85.2

### Accès par label avec `.loc[]`

Accès **explicite** par index ou étiquette. Très utile pour des filtres lisibles.

In [20]:
data.loc['b']  # Récupère la ligne avec l’index 'b'
data.loc[['a', 'c']]  # Récupère plusieurs lignes
data.loc['a':'c', ['name', 'score']]  # Ligne 'a' à 'c' et colonnes choisies

      name  score
a    Alice   88.5
b      Bob   92.3
c  Charlie   70.0

### Accès par position avec `.iloc[]`

Accès **implicite** par position numérique, comme avec un tableau.

In [21]:
data.iloc[1]         # Deuxième ligne
data.iloc[0:2, 1:3]  # Lignes 0 et 1, colonnes 1 et 2

    name  score
a  Alice   88.5
b    Bob   92.3

### Filtrer avec une condition

Créer un **masque booléen** pour filtrer les lignes selon une condition.

In [22]:
data[data['age'] > 30]
# Affiche les personnes de plus de 30 ans

   age     name  score
b   35      Bob   92.3
c   58  Charlie   70.0
d   44    David   85.2

### Combiner plusieurs conditions

Utiliser `&` (et), `|` (ou) avec des parenthèses.

In [23]:
data[(data['age'] > 30) & (data['score'] > 80)]

   age   name  score
b   35    Bob   92.3
d   44  David   85.2

### Ajouter une nouvelle colonne

On peut créer une colonne à la volée :

In [24]:
data['passed'] = data['score'] > 75
data

   age     name  score  passed
a   22    Alice   88.5    True
b   35      Bob   92.3    True
c   58  Charlie   70.0   False
d   44    David   85.2    True

## Opérations et alignement des index

Les opérations entre **Series** ou **DataFrame** s'alignent automatiquement sur les index.

- Si un index est manquant dans l'un des deux objets, le résultat sera **NaN** (Not a Number)
- On peut fournir une valeur par défaut avec `fill_value` quand un index est absent
- Les fonctions NumPy (comme `np.sqrt`, `np.exp`, etc.) fonctionnent directement sur les objets Pandas

### Opération avec des indices décalés

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

A + B

### Éviter les NaN avec `.add()` et `fill_value`

In [ ]:
A.add(B, fill_value=0)

### Utilisation de fonctions NumPy

In [ ]:
np.sqrt(A)

### Opérations sur DataFrame

In [ ]:
df1 = pd.DataFrame({
    "a": [1, 2, 3],
    "b": [4, 5, 6]
})

df2 = pd.DataFrame({
    "a": [7, 8, 9],
    "b": [10, 11, 12]
})

df1 + df2

### fill_value sur DataFrames

Définir les valeurs manquantes à `0` lors d'opérations entre DataFrames.

In [ ]:
df1.add(df2, fill_value=0)

## Combiner des Datasets

### Concaténation verticale (`axis=0`)

Par défaut, `pd.concat` concatène verticalement (empile les lignes).

In [43]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

print(pd.concat([ser1, ser2]))

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

### Concaténation horizontale (`axis=1`)

Forme un DataFrame en alignant les index.

In [44]:
print(pd.concat([ser1, ser2], axis=1))

     0    1
1    A  NaN
2    B  NaN
3    C  NaN
4  NaN    D
5  NaN    E
6  NaN    F

### Vérifier l'intégrité des index

L'option `verify_integrity=True` force une vérification des doublons dans les index. En cas de doublon, une erreur est levée.

In [7]:

x = pd.Series(['A', 'B'], index=[0, 1])
y = pd.Series(['C', 'D'], index=[3, 2])

# Lève une erreur car l'index 1 est dupliqué
pd.concat([x, y], verify_integrity=True)

0    A
1    B
3    C
2    D
dtype: object

### Ignorer les index avec `ignore_index`

Ignore les index d'origine et en crée de nouveaux numériques de 0 à n.

In [30]:
pd.concat([ser1, ser2], ignore_index=True)

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

### Garder les colonnes communes (`join='inner'`)

Concatène en ne gardant que les colonnes communes. Par défaut `join='outer'` (toutes les colonnes).

In [12]:
df5 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df6 = pd.DataFrame({'B': [5, 6], 'C': [7, 8]})

pd.concat([df5, df6], join='inner')

   B
0  3
1  4
0  5
1  6

### Filtrer les colonnes manuellement

> `join_axes` est **déprécié** dans les versions récentes de Pandas. On filtre les colonnes manuellement.

In [51]:
df5 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df6 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

pd.concat([df5, df6[df5.columns]], axis=0)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

## Fusion de DataFrames (merge)

> Équivalent du **JOIN** en SQL.

```python
pd.merge(df1, df2, how='inner', on='colonne_commune')
```

| Paramètre | Description |
|---|---|
| `left`, `right` | Les deux DataFrames à fusionner |
| `how` | Type de jointure : `'inner'`, `'left'`, `'right'`, `'outer'` |
| `on` | Colonne(s) commune(s) à utiliser pour la jointure |
| `left_on` | Colonne(s) du DataFrame de gauche à utiliser |
| `right_on` | Colonne(s) du DataFrame de droite à utiliser |
| `left_index` | Utilise l'index du DataFrame de gauche |
| `right_index` | Utilise l'index du DataFrame de droite |
| `suffixes` | Suffixes à ajouter pour les colonnes dupliquées (ex. `('_x', '_y')`) |
| `indicator=True` | Ajoute une colonne `_merge` pour indiquer l'origine des lignes |

### Jointure simple avec colonne commune

In [13]:
# DataFrame 1 avec un id
df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'A': ['A1', 'A2', 'A3'],
    'B': [10, 20, 30]
})

# DataFrame 2 avec un id
df2 = pd.DataFrame({
    'id': [3, 4, 5],
    'C': ['C3', 'C4', 'C5'],
    'D': [300, 400, 500]
})

pd.merge(df1, df2, on="id")

   id   A   B   C    D
0   3  A3  30  C3  300

### Types de jointures (`how`)

| Type | Description |
|---|---|
| `inner` | Garde les lignes avec des clés communes |
| `left` | Garde toutes les lignes de `df1`, et celles de `df2` si correspondance |
| `right` | Garde toutes les lignes de `df2`, et celles de `df1` si correspondance |
| `outer` | Garde tout (union), remplit les NaN si pas de correspondance |

In [55]:
pd.merge(df1, df2, on="id", how="outer")

   id    A     B    C      D
0   1   A1  10.0  NaN    NaN
1   2   A2  20.0  NaN    NaN
2   3   A3  30.0   C3  300.0
3   4  NaN   NaN   C4  400.0
4   5  NaN   NaN   C5  500.0

### Colonnes avec des noms différents

In [57]:
pd.merge(df1, df2, left_on="id", right_on="id")

   id   A   B   C    D
0   3  A3  30  C3  300

### Fusionner sur les index

In [16]:
# signifie que la fusion doit être effectuée en utilisant les index des deux DataFrames
pd.merge(df1, df2, left_index=True, right_index=True)

   id_x   A   B  id_y   C    D
0     1  A1  10     3  C3  300
1     2  A2  20     4  C4  400
2     3  A3  30     5  C5  500

### Ajouter un indicateur

In [59]:
pd.merge(df1, df2, on="id", how="outer", indicator=True)

   id    A     B    C      D      _merge
0   1   A1  10.0  NaN    NaN   left_only
1   2   A2  20.0  NaN    NaN   left_only
2   3   A3  30.0   C3  300.0        both
3   4  NaN   NaN   C4  400.0  right_only
4   5  NaN   NaN   C5  500.0  right_only

### Gérer les colonnes dupliquées

In [60]:
pd.merge(df1, df2, on="id", suffixes=('_gauche', '_droite'))

   id   A   B   C    D
0   3  A3  30  C3  300

## Analyse statistique avec `describe()`

`describe()` fournit un résumé statistique des colonnes numériques.

In [9]:
df = pd.DataFrame({
    'age': [22, 35, 58, 41],
    'taille': [1.65, 1.80, 1.75, 1.60],
    'nom': ['Alice', 'Bob', 'Charlie', 'David']
})

df.describe()

             age    taille
count   4.000000  4.000000
mean   39.000000  1.700000
std    14.944341  0.091287
min    22.000000  1.600000
25%    31.750000  1.637500
50%    38.000000  1.700000
75%    45.250000  1.762500
max    58.000000  1.800000

| Paramètre | Description |
|---|---|
| `include='all'` | Inclut toutes les colonnes (numériques, objets, booléens, etc.) |
| `include=['object']` | Décrit uniquement les colonnes de type `object` (texte, catégories, etc.) |
| `exclude=['number']` | Exclut les colonnes numériques |
| `percentiles=[...]` | Personnalise les centiles à afficher (par défaut : 25%, 50%, 75%) |

In [10]:
df.describe(include='all')
df.describe(include=['object'])
df.describe(percentiles=[.1, .5, .9])

             age    taille
count   4.000000  4.000000
mean   39.000000  1.700000
std    14.944341  0.091287
min    22.000000  1.600000
10%    25.900000  1.615000
50%    38.000000  1.700000
90%    52.900000  1.785000
max    58.000000  1.800000

## Autres méthodes statistiques

| Méthode | Description |
|---|---|
| `df.mean()` | Moyenne par colonne |
| `df.median()` | Médiane par colonne |
| `df.std()` | Écart-type |
| `df.var()` | Variance |
| `df.min()` | Valeur minimale |
| `df.max()` | Valeur maximale |
| `df.sum()` | Somme |
| `df.count()` | Nombre de valeurs non nulles |
| `df.mode()` | Valeur(s) la/les plus fréquente(s) |
| `df.quantile(0.25)` | 1er quartile (25%) |
| `df.corr()` | Matrice de corrélation entre colonnes numériques |

In [39]:
df["age"].mean()       # Moyenne des âges
df["age"].median()     # Médiane
df["age"].std()        # Écart-type
df["age"].quantile(0.75)  # 3e quartile (75%)

np.float64(45.25)

## L'agrégation

Résumer des données à l'aide de fonctions comme `sum()`, `mean()`, `count()`, etc. L'agrégation est souvent utilisée avec `groupby()` pour obtenir des statistiques par groupe.

In [ ]:
df["colonne"].sum()
df["colonne"].mean()
df["colonne"].min()
df["colonne"].max()
df["colonne"].count()
df["colonne"].nunique()   # nombre de valeurs uniques

## GroupBy

`groupby()` permet de regrouper les données selon une ou plusieurs colonnes pour effectuer des calculs par groupe.

In [40]:
df = pd.DataFrame({
    'genre': ['H', 'F', 'F', 'H', 'F'],
    'age': [23, 45, 36, 52, 33],
    'revenu': [1000, 1200, 1300, 1100, 1250]
})

# Moyenne de l'âge et du revenu par genre
df.groupby("genre")[["age", "revenu"]].mean()

        age  revenu
genre
F      38.0  1250.0
H      37.5  1050.0

### `agg()` pour plusieurs agrégations

| Méthode | Description |
|---|---|
| `groupby()` | Regroupe les lignes selon une ou plusieurs colonnes |
| `agg()` | Applique une ou plusieurs fonctions sur chaque groupe |
| `reset_index()` | Remet l'index à plat après un `groupby()` |
| `as_index=False` | Évite que la colonne de regroupement devienne l'index |

In [ ]:
df[ "revenu" ] .agg ( ["min", "max", "mean"] )

min     1000.0
max     1300.0
mean    1170.0
Name: revenu, dtype: float64

In [ ]:
# Exemple de DataFrame
df = pd.DataFrame({
    'genre': ['Homme', 'Femme', 'Homme', 'Femme', 'Homme'],
    'age': [25, 30, 35, 40, 45],
    'revenu': [2000, 3000, 2500, 4000, 3500]
})

# GroupBy avec agrégation multiple
result = df.groupby("genre", as_index=False).agg(
    {
    "age": "mean",  # Moyenne des âges
    "revenu": ["min", "max", "mean"]  # Min, Max, et Moyenne des revenus
    }
    )

print(result)

   genre   age revenu
          mean    min   max         mean
0  Femme  35.0   3000  4000  3500.000000
1  Homme  35.0   2000  3500  2666.666667