# Sélectionner des données

En utilisant les **crochets** `[]`, on peut préciser le nom de la colonne que l'on souhaite récupérer :

```python
df["email"]
```

- On peut chaîner la méthode **`head()`** pour n'afficher que les premières valeurs.
- Si le nom de la colonne contient des **espaces**, cette notation est **obligatoire**.

In [ ]:
import pandas as pd

df = pd.read_csv("../data.csv")

df["email"].head()

0     malders0@shop-pro.jp
1       hharridge1@gnu.org
2    ekilminster2@etsy.com
3         gbrantl3@umn.edu
4      kbeasant4@jigsy.com
5     tbraybrooke5@umn.edu
6       akencott6@phoca.cz
7         cfeasley7@ed.gov
8    wheersema8@tumblr.com
9    ggookes9@amazon.co.uk
Name: email, dtype: object

## Accès par attribut (notation pointée)

On peut également récupérer une colonne avec la **notation pointée**, à condition que le nom de la colonne **ne contienne pas d'espaces** :

```python
df.email
```

La méthode **`head()`** fonctionne aussi avec cette syntaxe.

In [ ]:
df.email
df.email.head()

0            malders0@shop-pro.jp
1              hharridge1@gnu.org
2           ekilminster2@etsy.com
3                gbrantl3@umn.edu
4             kbeasant4@jigsy.com
                  ...
995          derrigorn@elpais.com
996         arastallro@toplist.cz
997    bstickelsrp@cloudflare.com
998        ptesoerq@rakuten.co.jp
999         rpringuerrr@house.gov
Name: email, Length: 1000, dtype: object

## DataFrame vs Series

Pandas manipule deux types d'objets :

| Type | Description |
|------|-------------|
| **DataFrame** | Tableau complet à **2 dimensions** (lignes + colonnes) |
| **Series** | Une seule colonne du DataFrame, structure **1D** |

> Cette distinction est importante : certaines opérations ne sont disponibles que sur l'un ou l'autre type.

On peut utiliser la fonction **`type()`** pour vérifier le type d'un objet :

```python
type(df)        # → DataFrame
type(df.email)  # → Series
```

In [6]:
#type(df)

type(df.email)

pandas.core.series.Series

### Opérations spécifiques aux Series

| Opération | Description |
|-----------|-------------|
| `str.` | Méthodes spécifiques aux chaînes de caractères (ex : `str.lower()`) |
| `dt.` | Méthodes spécifiques aux dates (ex : `dt.year`, `dt.month`) |
| `map()` | Appliquer une fonction **valeur par valeur** |
| `Series[index]` | Accès direct à une valeur (pas besoin de `.loc[]`) |

### Opérations spécifiques aux DataFrames

| Opération | Description |
|-----------|-------------|
| `df['col']` ou `df[['col1', 'col2']]` | Sélection de colonnes |
| `df.loc[row, col]`, `df.iloc[...]` | Sélections avancées ligne + colonne |
| `groupby()` | Regroupement par colonnes |
| `pivot_table()` | Création de tableaux croisés dynamiques |
| `merge()`, `join()` | Fusionner plusieurs DataFrames |
| `drop(columns=...)` | Supprimer des colonnes entières |
| `corr()`, `cov()` | Corrélation / covariance entre colonnes numériques |
| `duplicated()` / `drop_duplicates()` | Identifier / retirer les doublons sur plusieurs colonnes |
| `set_index()` / `reset_index()` | Modifier ou réinitialiser l'index |

### Opérations communes

Ces opérations fonctionnent à la fois sur les **Series** et les **DataFrames** :

| Opération | Description |
|-----------|-------------|
| `head(n)` / `tail(n)` | Affiche les premières / dernières lignes |
| `shape`, `size`, `ndim` | Dimensions, taille, nombre d'axes |
| `describe()` | Statistiques de base (moyenne, min, max, etc.) |
| `value_counts()` | Compter les occurrences (surtout utile en Series) |
| `astype()` | Changer le type de données |
| `isnull()`, `notnull()` | Détection de valeurs manquantes |
| `apply()` | Appliquer une fonction (à chaque ligne/élément) |
| `sort_values()` | Trier par valeur |
| `unique()`, `nunique()` | Valeurs uniques et nombre de valeurs uniques |
| `mean()`, `sum()`, etc. | Calculs numériques simples |
| `plot()` | Graphiques (via matplotlib ou seaborn) |

## Slicing avec les crochets

On peut utiliser les **crochets** pour récupérer un **intervalle de lignes**, comme un **slice** sur les listes en Python :

```python
df[10:20]  # lignes d'index 10 à 19 (borne max exclue)
```

In [7]:
df[10:20]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
10,11,03/11/2021,Lief,Woodcraft,lwoodcrafta@sitemeter.com,Male,201.76.240.51,Canada,$5.71,NaN
11,12,03/16/2021,Bailie,Wyman,bwymanb@lulu.com,Male,222.60.138.222,United States,$3.15,20.0
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0
13,14,03/24/2021,Cull,Vassie,cvassied@unblog.fr,NaN,18.203.61.94,France,$5.97,20.0
14,15,03/21/2021,Oralie,Maryon,omaryone@va.gov,Female,215.248.16.198,United States,$4.53,20.0
15,16,03/24/2021,Julina,Faint,jfaintf@amazon.co.jp,Female,96.193.4.151,United States,$4.10,20.0
16,17,03/27/2021,Eve,Allaway,eallawayg@ebay.co.uk,Female,184.107.59.156,United States,$6.44,20.0
17,18,03/20/2021,Esta,Boulden,ebouldenh@posterous.com,NaN,220.109.140.190,United States,$3.16,20.0
18,19,03/16/2021,Judye,Behan,jbehani@google.es,Female,27.196.2.18,France,$4.90,20.0
19,20,03/01/2021,Sibeal,Mounch,smounchj@rakuten.co.jp,Male,218.17.7.177,Canada,$5.82,20.0

## Sélection avec `loc[]`

La méthode **`loc[]`** permet de sélectionner des lignes par leur **index** :

```python
df.loc[10:13]
```

> **Différence clé** : contrairement au slicing classique, la **borne maximale est incluse** avec `loc[]`.

In [8]:
df.loc[10:13]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
10,11,03/11/2021,Lief,Woodcraft,lwoodcrafta@sitemeter.com,Male,201.76.240.51,Canada,$5.71,NaN
11,12,03/16/2021,Bailie,Wyman,bwymanb@lulu.com,Male,222.60.138.222,United States,$3.15,20.0
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0
13,14,03/24/2021,Cull,Vassie,cvassied@unblog.fr,NaN,18.203.61.94,France,$5.97,20.0

## Changer l'index et utiliser `loc[]`

Avec **`set_index()`**, on peut remplacer l'index numérique par une colonne (ex : `"email"`). On utilise ensuite **`loc[]`** pour cibler des lignes par cette nouvelle clé :

```python
df_email = df.set_index("email")
df_email.loc["lwoodcrafta@sitemeter.com"]
```

> Lorsqu'on cible un **élément précis**, `loc[]` renvoie un objet **Series**.

Pour convertir le résultat en objet Python natif, on peut utiliser **`.values.tolist()`**.

In [ ]:
df_email = df.set_index("email")

df_email.loc["lwoodcrafta@sitemeter.com"]

# on a la possibilité de passer plusieurs informations en paramètre
# df_email.loc["lwoodcrafta@sitemeter.com","lwoodcrafta@sitemeter.com","lwoodcrafta@sitemeter.com"]