# Filtrer les données

In [2]:
import pandas as pd

df = pd.read_csv("../data.csv")

# dans le cas d'une condition simple on va retrouver des booleans en guise de reponse
df["gender"] == "Male"

0       True
1      False
2       True
3      False
4       True
       ...
995    False
996    False
997     True
998     True
999    False
Name: gender, Length: 1000, dtype: bool

## Appliquer un filtre

Pour récupérer les éléments qui correspondent à une condition, on passe la **condition** directement à l'intérieur des **crochets** `[]` du DataFrame.

On obtient ainsi uniquement les lignes où la condition est `True`.

In [3]:
df[df["gender"] == "Male"]

# on peut enregistrer le filtre 

female_filter = df["gender"] == "Female"

df[female_filter]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
5,6,03/25/2021,Titos,Braybrooke,tbraybrooke5@umn.edu,Female,173.100.21.179,United States,$5.82,NaN
6,7,03/14/2021,Ava,Kencott,akencott6@phoca.cz,Female,118.251.45.43,Canada,$6.29,NaN
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0
...,...,...,...,...,...,...,...,...,...,...
985,986,03/29/2021,Yvonne,Longworthy,ylongworthyrd@163.com,Female,9.59.123.181,France,$9.16,NaN
988,989,03/07/2021,Yves,Botler,ybotlerrg@miitbeian.gov.cn,Female,148.191.87.121,United States,$6.10,20.0
994,995,03/17/2021,Carolyne,Bruntjen,cbruntjenrm@reference.com,Female,7.29.168.78,France,$5.68,20.0
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0

## Filtrer avec `isin()`

Pour vérifier si des valeurs font partie d'une liste donnée, on utilise la méthode **`isin()`**.

In [ ]:
# on peut passer une liste ou un tuple
# on va retrouver des booleans en guise de reponse
# ne pas hesiter a regarder la documentation de pandas en fonction de ce que vous voulez faire

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html

# ici une liste
df["country"].isin(("France", "Germany"))

# ici un tuple
df["country"].isin(["France", "Germany"])

country_filter = df["country"].isin(["France", "Germany"])

df[country_filter]

## Attention aux types de données

La colonne **`price_paid`** est de type `str` (ex: `"$5.36"`). On ne peut donc pas directement appliquer un filtre numérique dessus.

In [ ]:
df[df["price_paid"] > 6]

# TypeError: '>' not supported between instances of 'str' and 'int'

### Conversion de type avant filtrage

On peut convertir la colonne en supprimant le caractère `$` puis en changeant le type en `float`.

In [ ]:
df_test = df.copy()
df_test.price_paid = df_test.price_paid.apply(lambda x: x.replace("$", ""))
df_test.price_paid = df_test.price_paid.astype(float)
df_test[df_test["price_paid"] > 6]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0